spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: your-tenant-id
        credential:
          client-id: your-client-id
          client-secret: your-client-secret

server:
  port: 8080
  forward-headers-strategy: native